# SPDX-License-Identifier: LGPL-3.0-only
# Copyright (c) 2026 Mirrowel

"""
Configuration module for the rotator library.

Exports all centralized defaults for use across the library.
"""

from .defaults import (
    # Rotation & Selection
    DEFAULT_ROTATION_MODE,
    DEFAULT_ROTATION_TOLERANCE,
    DEFAULT_MAX_RETRIES,
    DEFAULT_GLOBAL_TIMEOUT,
    # Tier & Priority
    DEFAULT_TIER_PRIORITY,
    DEFAULT_SEQUENTIAL_FALLBACK_MULTIPLIER,
    DEFAULT_MAX_CONCURRENT_PER_KEY,
    DEFAULT_MAX_CONCURRENT_PER_KEY_BALANCED,
    DEFAULT_MAX_CONCURRENT_PER_KEY_SEQUENTIAL,
    DEFAULT_OPTIMAL_CONCURRENT_PER_KEY,
    DEFAULT_OPTIMAL_CONCURRENT_PER_KEY_BALANCED,
    DEFAULT_OPTIMAL_CONCURRENT_PER_KEY_SEQUENTIAL,
    # Fair Cycle Rotation
    DEFAULT_FAIR_CYCLE_ENABLED,
    DEFAULT_FAIR_CYCLE_TRACKING_MODE,
    DEFAULT_FAIR_CYCLE_CROSS_TIER,
    DEFAULT_FAIR_CYCLE_DURATION,
    DEFAULT_FAIR_CYCLE_QUOTA_THRESHOLD,
    DEFAULT_FAIR_CYCLE_RESET_COOLDOWN_THRESHOLD,
    DEFAULT_EXHAUSTION_COOLDOWN_THRESHOLD,
    # Custom Caps
    DEFAULT_CUSTOM_CAP_COOLDOWN_MODE,
    DEFAULT_CUSTOM_CAP_COOLDOWN_VALUE,
    # Cooldown & Backoff
    COOLDOWN_BACKOFF_TIERS,
    COOLDOWN_BACKOFF_MAX,
    COOLDOWN_AUTH_ERROR,
    COOLDOWN_TRANSIENT_ERROR,
    COOLDOWN_RATE_LIMIT_DEFAULT,
    # Small Cooldown Auto-Retry
    DEFAULT_SMALL_COOLDOWN_RETRY_THRESHOLD,
    DEFAULT_TRANSIENT_RETRY_DELAY,
    DEFAULT_TRANSIENT_RETRY_JITTER,
    DEFAULT_STREAM_RETRY_ON_REASONING_ONLY,
    DEFAULT_RATE_LIMIT_MAX_RETRY_AFTER,
    DEFAULT_QUOTA_FAILURE_THRESHOLD,
)

__all__ = [
    # Rotation & Selection
    "DEFAULT_ROTATION_MODE",
    "DEFAULT_ROTATION_TOLERANCE",
    "DEFAULT_MAX_RETRIES",
    "DEFAULT_GLOBAL_TIMEOUT",
    # Tier & Priority
    "DEFAULT_TIER_PRIORITY",
    "DEFAULT_SEQUENTIAL_FALLBACK_MULTIPLIER",
    "DEFAULT_MAX_CONCURRENT_PER_KEY",
    "DEFAULT_MAX_CONCURRENT_PER_KEY_BALANCED",
    "DEFAULT_MAX_CONCURRENT_PER_KEY_SEQUENTIAL",
    "DEFAULT_OPTIMAL_CONCURRENT_PER_KEY",
    "DEFAULT_OPTIMAL_CONCURRENT_PER_KEY_BALANCED",
    "DEFAULT_OPTIMAL_CONCURRENT_PER_KEY_SEQUENTIAL",
    # Fair Cycle Rotation
    "DEFAULT_FAIR_CYCLE_ENABLED",
    "DEFAULT_FAIR_CYCLE_TRACKING_MODE",
    "DEFAULT_FAIR_CYCLE_CROSS_TIER",
    "DEFAULT_FAIR_CYCLE_DURATION",
    "DEFAULT_FAIR_CYCLE_QUOTA_THRESHOLD",
    "DEFAULT_FAIR_CYCLE_RESET_COOLDOWN_THRESHOLD",
    "DEFAULT_EXHAUSTION_COOLDOWN_THRESHOLD",
    # Custom Caps
    "DEFAULT_CUSTOM_CAP_COOLDOWN_MODE",
    "DEFAULT_CUSTOM_CAP_COOLDOWN_VALUE",
    # Cooldown & Backoff
    "COOLDOWN_BACKOFF_TIERS",
    "COOLDOWN_BACKOFF_MAX",
    "COOLDOWN_AUTH_ERROR",
    "COOLDOWN_TRANSIENT_ERROR",
    "COOLDOWN_RATE_LIMIT_DEFAULT",
    # Small Cooldown Auto-Retry
    "DEFAULT_SMALL_COOLDOWN_RETRY_THRESHOLD",
    "DEFAULT_TRANSIENT_RETRY_DELAY",
    "DEFAULT_TRANSIENT_RETRY_JITTER",
    "DEFAULT_STREAM_RETRY_ON_REASONING_ONLY",
    "DEFAULT_RATE_LIMIT_MAX_RETRY_AFTER",
    "DEFAULT_QUOTA_FAILURE_THRESHOLD",
]
